### ISSUE TITLE
how can I contribute on the repo?

### ISSUE THREAD

**Issue by shibuiwilliam** [Minyus/pipelinex#1]
I would recommend to add a CONTRIBUTING guideline to send PR on the repository. 
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by Minyus** [comment]
Thank you for your recommendation. I added [CONTRIBUTING.md](https://github.com/Minyus/pipelinex/blob/master/CONTRIBUTING.md) .

**Comment by shibuiwilliam** [comment]
thanks!
