### ISSUE TITLE
Licence clarity

### ISSUE THREAD

**Issue by cariad** [Minyus/pipelinex#11]
Hi! Your LICENSE file has mandatory notices for code you've imported, but I can't figure out which licence (if any?) your original code has been published under. Can you clarify, please?

Thank you!

**Comment by Minyus** [comment]
Hi @cariad , thank you for your question. 

I clarified the license at:
https://github.com/Minyus/pipelinex/blob/master/LICENSE

PipelineX is under mainly Apache License 2.0 and partially MIT and BSD 3-Clause License.

You can use PipelineX for commercial applications.

I'd appreciate it if you can let me know your use case so I can consider to list it in the document of PipelineX if appropriate.

**Comment by cariad** [comment]
That's fantastic, thank you! 🎉 

Our use case is a bit vague at the moment. I work with a data scientist who loves this project, and I wanted to make sure we're legally okay to take inspiration from you. And that updated license is perfect -- thank you!
