### ISSUE TITLE
HatchDict: Is there a way to reference variables as parameters?

### ISSUE THREAD

**Issue by npow** [Minyus/pipelinex#15]
Hi, came across `HatchDict` which has been super useful so far! I'm trying to reference variables in parameters. For example, below I have the variable `C` defined in some file already. Is there a way to achieve this with HatchDict? This is a contrived example, but it would be pretty useful for parameters like long lists.

```
model:
  =: sklearn.linear_classifier.SGDClassifier
  C: =: mylib.constants.C
```

**Comment by Minyus** [comment]
Yes, you can write like this:

```python
from pipelinex import HatchDict

params_yaml="""
model:
  =: sklearn.linear_model.SGDClassifier
  alpha: 
    =: numpy.pi 
"""
model = HatchDict(parameters).get("model")

print(model)
```

Output:
```
SGDClassifier(alpha=3.141592653589793)
```
